---
title: "other_result_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load packages}
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(purrr)

```
#Remove this when CSV Files are fixed!



```{r load & preparedata}
# load results overviews
group_a_pData <- as.data.frame(read_csv('../data/merged_data/pData/imputed/merged_imputed_pData.csv', lazy = TRUE))

ov_results_cBoost <- as.data.frame(read_csv('../results_modelling_ovs/ov_GBoost.csv', lazy = TRUE))
ov_results_coxPas <- as.data.frame(read_csv('../results_modelling_ovs/ov_coxPAS.csv', lazy = TRUE))
ov_results_coxph <- as.data.frame(read_csv('../results_modelling_ovs/ov_coxph.csv', lazy = TRUE))
ov_results_DeepSurv <- as.data.frame(read_csv('../results_modelling_ovs/ov_DeepSurv.csv', lazy = TRUE))
ov_results_prio <- as.data.frame(read_csv('../results_modelling_ovs/ov_prio.csv', lazy = TRUE))
ov_results_rsf <- as.data.frame(read_csv('../results_modelling_ovs/ov_rsf.csv', lazy = TRUE))

ordered_datasets <- c("AutoEncoder", "pData_AutoEncoder", "Imputed", "pData_Imputed", "Intersection", "pData_Intersection", "pData")
# Reorder the dataset column and sort the data frame accordingly
ov_results_cBoost <- ov_results_cBoost %>%
  mutate(dataset = factor(dataset, levels = ordered_datasets)) %>%
  arrange(dataset)
ov_results_coxph <- ov_results_coxph %>%
  mutate(dataset = factor(dataset, levels = ordered_datasets)) %>%
  arrange(dataset)
ov_results_DeepSurv <- ov_results_DeepSurv %>%
  mutate(dataset = factor(dataset, levels = ordered_datasets)) %>%
  arrange(dataset)
ov_results_rsf <- ov_results_rsf %>%
  mutate(dataset = factor(dataset, levels = ordered_datasets)) %>%
  arrange(dataset)

ov_results_cBoost$dataset <- ordered_datasets
ov_results_coxph$dataset <- ordered_datasets
ov_results_DeepSurv$dataset <- ordered_datasets
ov_results_rsf$dataset <- ordered_datasets



### Prepare detailed Train Data Results
## Filter for the best models only w.r.t exprs based trainin sets, as comparison will be with ffpe score

#cBoost load and filter and find best dataset
splits_results_cBoost <- as.data.frame(read_csv('../results_modelling_splits/splits_BBoost.csv', lazy = TRUE))
subset_splits_results_cBoost <- splits_results_cBoost %>% filter(dataset %in% c("AutoEncoder", "Intersection", "Imputed"))
splits_best_cBoost <- subset_splits_results_cBoost %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# coxph load and filter and find best dataset
splits_results_coxph <- as.data.frame(read_csv('../results_modelling_splits/splits_coxph.csv', lazy = TRUE))
subset_splits_results_coxph <- splits_results_coxph %>%
  filter(dataset %in% c("AutoEncoder","Intersection", "Imputed"))
splits_best_coxph <- subset_splits_results_coxph %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>% 
  ungroup()



# DeepSurv load and filter and find best dataset
splits_results_DeepSurv <- as.data.frame(read_csv('../results_modelling_splits/splits_DeepSurv.csv', lazy = TRUE))
subset_splits_results_DeepSurv <- splits_results_DeepSurv %>%
  filter(dataset %in% c("AutoEncoder","Intersection", "Imputed"))
splits_best_DeepSurv <- subset_splits_results_DeepSurv %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# rsf load and filter and find best dataset
splits_results_rsf <- as.data.frame(read_csv('../results_modelling_splits/splits_rsf.csv', lazy = TRUE))
subset_splits_results_rsf <- splits_results_rsf %>%
  filter(dataset %in% c("AutoEncoder","Intersection", "Imputed"))
splits_best_rsf <- subset_splits_results_rsf %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# prio load and filter and find best dataset
splits_results_prio <- as.data.frame(read_csv('../results_modelling_splits/splits_prio.csv', lazy = TRUE))
subset_splits_results_prio <- splits_results_prio %>%
  filter(dataset %in% c("gene_blocks"))
splits_best_prio <- subset_splits_results_prio %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()





# the same but this time allowing for all mdoels, not just gene based
# cBoost load and find best dataset
splits_results_cBoost_all_data <- as.data.frame(read_csv('../results_modelling_splits/splits_GBoost.csv', lazy = TRUE))
splits_best_cBoost_all_data <- splits_results_cBoost_all_data %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# coxph load and find best dataset
splits_results_coxph_all_data <- as.data.frame(read_csv('../results_modelling_splits/splits_coxph.csv', lazy = TRUE))
splits_best_coxph_all_data <- splits_results_coxph_all_data %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# DeepSurv load and find best dataset
splits_results_DeepSurv_all_data <- as.data.frame(read_csv('../results_modelling_splits/splits_DeepSurv.csv', lazy = TRUE))
splits_best_DeepSurv_all_data <- splits_results_DeepSurv_all_data %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# rsf load and find best dataset
splits_results_rsf_all_data <- as.data.frame(read_csv('../results_modelling_splits/splits_rsf.csv', lazy = TRUE))
splits_best_rsf_all_data <- splits_results_rsf_all_data %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()

# prio load and find best dataset
splits_results_prio_all_data <- as.data.frame(read_csv('../results_modelling_splits/splits_prio.csv', lazy = TRUE))
splits_best_prio_all_data <- splits_results_prio_all_data %>%
  group_by(test_cohort) %>%
  slice_max(order_by = ci, n = 1) %>%
  ungroup()


# coxPas load and filter and find best dataset
splits_results_coxPas <- as.data.frame(read_csv('../results_modelling_splits/splits_coxPAS.csv', lazy = TRUE))
splits_best_coxPas <- splits_results_coxPas




splits_results_score <- as.data.frame(read_csv('../results_modelling_splits/splits_score_cindices.csv', lazy = TRUE))
colnames(splits_results_score)[colnames(splits_results_score) == "c_index"] <- "ci"
colnames(splits_results_score)[colnames(splits_results_score) == "cohort"] <- "test_cohort"
splits_best_score <- splits_results_score

all_ov_df <- c("ov_results_cBoost", "ov_results_coxPas", "ov_results_coxph",
               "ov_results_DeepSurv", "ov_results_prio", "ov_results_rsf")

# prepare exprs based models
ov_results_cBoost_exprs_models <- ov_results_cBoost[c(1, 3, 5),]
ov_results_coxph_exprs_models <- ov_results_coxph[c(1, 3, 5),]
ov_results_DeepSurv_exprs_models <- ov_results_DeepSurv[c(1, 3, 5),]
ov_results_rsf_exprs_models <- ov_results_rsf[c(1, 3, 5),]
ov_results_prio_exprs_models <- ov_results_prio[c(2),]


## survival data:
# 1) Read survival data
coxph_survival_data <- read_csv("../data/survival_data/predicted_survival_curves_coxph.csv")
ae_deep_surv_survival_data_coh1_high_risk <- read_csv("../data/survival_data/predicted_survival_curves_cohort1_high_risk.csv")
ae_deep_surv_survival_data_coh1_low_risk  <- read_csv("../data/survival_data/predicted_survival_curves_cohort1_low_risk.csv")
ae_deep_surv_survival_data_coh2_high_risk <- read_csv("../data/survival_data/predicted_survival_curves_cohort2_high_risk.csv")
ae_deep_surv_survival_data_coh2_low_risk  <- read_csv("../data/survival_data/predicted_survival_curves_cohort2_low_risk.csv")

# 2) Compute row-wise averages (skipping first column "time")
ae_surv_coh1_high_vec <- rowMeans(ae_deep_surv_survival_data_coh1_high_risk[ , -1], na.rm = TRUE)
ae_surv_coh1_low_vec  <- rowMeans(ae_deep_surv_survival_data_coh1_low_risk[ , -1],  na.rm = TRUE)
ae_surv_coh2_high_vec <- rowMeans(ae_deep_surv_survival_data_coh2_high_risk[ , -1], na.rm = TRUE)
ae_surv_coh2_low_vec  <- rowMeans(ae_deep_surv_survival_data_coh2_low_risk[ , -1],  na.rm = TRUE)
```



```{r Defining model subsets}
all_models <- c("GBoost", "CoxPN", "CoxPH", "DeepSurv","PrioLasso", "RSF")
models_expr_based_only <- c("GBoost", "CoxPH","DeepSurv" ,"PrioLasso", "RSF")

```


```{r Boxplots best Results by Cohorts}
# mapping for group a cohorts only
rename_map <- c(
  "Atlanta_2014_Long" = "Cohort 1",
  "Belfast_2018_Jain" = "Cohort 2",
  "CamCap_2016_Ross_Adams" = "Cohort 3",
  "CancerMap_2017_Luca" = "Cohort 4",
  "CPC_GENE_2017_Fraser" = "Cohort 5",
  "CPGEA_2020_Li" = "Cohort 6",
  "DKFZ_2018_Gerhauser" = "Cohort 7",
  "MSKCC_2010_Taylor" = "Cohort 8",
  "Stockholm_2016_Ross_Adams" = "Cohort 9"
)
### Prepare the data for the first boxplot
## First boxplot comparing only exprs based models when possible, but still incl.
## CoxPAS und Priority Lasso
splits_best_cBoost$model <- "GBoost"
splits_best_coxPas$model <- "CoxPN"
splits_best_coxph$model <- "CoxPH"
splits_best_prio$model <- "PrioLasso"
splits_best_rsf$model <- "RSF"
splits_best_DeepSurv$model <- "DeepSurv"
splits_best_score$model <- "ProstaTrend-ffpe"


all_best_splits_data <- bind_rows(
  splits_best_cBoost,
  splits_best_coxPas,
  splits_best_coxph,
  splits_best_prio,
  splits_best_rsf,
  splits_best_DeepSurv,
  splits_best_score
)



# rename
all_best_splits_data <- all_best_splits_data %>%
  mutate(test_cohort = rename_map[test_cohort])


### Prepare the data for the second boxplot
## Second box plot compares best models on all data sets with ffpe score
splits_best_cBoost_all_data$model <- "GBoost"
splits_best_coxph_all_data$model <- "CoxPH"
splits_best_rsf_all_data$model <- "RSF"
splits_best_DeepSurv_all_data$model <- "DeepSurv"
splits_best_prio_all_data$model <- "PrioLasso"



all_best_splits_data_all_data_sets <- bind_rows(
  splits_best_cBoost_all_data,
  splits_best_coxPas,
  splits_best_coxph_all_data,
  splits_best_prio_all_data,
  splits_best_rsf_all_data,
  splits_best_DeepSurv_all_data,
  splits_best_score
)




# rename
all_best_splits_data_all_data_sets <- all_best_splits_data_all_data_sets %>%
  mutate(test_cohort = rename_map[test_cohort])




```

```{r plot the Boxplots }
plot1 <- ggplot(all_best_splits_data[,1:5], aes(x = test_cohort, y = ci)) +
  geom_boxplot(aes(fill = "Other Models"), outlier.shape = NA) + 
  geom_jitter(
    data = all_best_splits_data %>% filter(model == "ProstaTrend-ffpe"),
    aes(color = model), width = 0.2, alpha = 0.7
  ) +
  scale_color_manual("", values = c(
    "ProstaTrend-ffpe" = "#0c4252"
  )) +
  scale_fill_manual("", values = c(
    "Other Models" = "#ffcd66"
  )) +
  labs(
    title = "Best Model per Model Class vs. ProstaTrend-ffpe - Comparison by Cohort",
    x = "Cohorts in Group A",
    y = "C-Index"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 12),  
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )



plot2 <- ggplot(all_best_splits_data_all_data_sets[,1:5], aes(x = test_cohort, y = ci)) +
  geom_boxplot(aes(fill = "Other Models"), outlier.shape = NA) + 
  geom_jitter(
    data = all_best_splits_data %>% filter(model == "ProstaTrend-ffpe"),
    aes(color = model), width = 0.2, alpha = 0.7
  ) +
  scale_color_manual("", values = c(
    "ProstaTrend-ffpe" = "#0c4252"
  )) +
  scale_fill_manual("", values = c(
    "Other Models" = "#ffcd66"
  )) +
  labs(
    title = "Best Model per Model Class vs. ProstaTrend-ffpe - Comparison by Cohort",
    x = "Cohorts in Group A",
    y = "C-Index"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 12),  
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )
```

```{r correlation between model performance and % of events }

# Berechnung der mean werte pro Test-Cohort
mean_data <- all_best_splits_data_all_data_sets[,1:5] %>%
  group_by(test_cohort) %>%
  summarise(mean_ci = mean(ci, na.rm = TRUE))


group_a_pData <- group_a_pData %>%
  mutate(cohort = sub("\\..*", "", ...1))
group_a_pData <- group_a_pData %>%
  mutate(cohort = recode(cohort, !!!rename_map))

bcr_summary <- group_a_pData %>%
  group_by(cohort) %>%
  summarise(BCR_Percentage = mean(BCR_STATUS == 1, na.rm = TRUE) * 100) %>%
  arrange(desc(BCR_Percentage))
bcr_summary$BCR_Percentage <- 100 - bcr_summary$BCR_Percentage  

merged_data <- bcr_summary %>%
  inner_join(mean_data, by = c("cohort" = "test_cohort"))
#used spearman because of the small data set and interest in monoton relation
bcr_performance_cor <- cor(merged_data$BCR_Percentage, merged_data$mean_ci, method = "spearman")

#### Plot Goal: Using mean performance(mean w.r.t. to the input data set) of each model type
# on each cohort to check whether to get the correlation for the different model types 

models_list <- list(
  "GBoost" = splits_results_cBoost,
  "DeepSurv" = splits_results_DeepSurv,
  "RSF" = splits_results_rsf,
  "CoxPN" = splits_results_coxPas,
  "PrioLasso" = splits_results_prio,
  "ProstaTrend-ffpe" = splits_results_score,
  "CoxPH" = splits_results_coxph
)

compute_mean_ci <- function(df) {
  df %>%
    group_by(test_cohort) %>%
    summarise(mean_ci = mean(ci, na.rm = TRUE), .groups = "drop")
}

mean_ci_list <- map(models_list, compute_mean_ci)

mean_ci_data <- reduce(mean_ci_list, full_join, by = "test_cohort")

colnames(mean_ci_data)[-1] <- names(models_list)

mean_ci_data <- mean_ci_data %>%
  mutate(test_cohort = recode(test_cohort, !!!rename_map))

merged_mean_ci_data <- mean_ci_data %>%
  inner_join(bcr_summary, by = c("test_cohort" = "cohort"))

model_columns <- colnames(merged_mean_ci_data)[2:(ncol(merged_mean_ci_data) - 1)]

# Berechnung der Pearson-Korrelation zwischen jeder Modellspalte und der BCR-Spalte
correlations <- sapply(model_columns, function(model) {
  cor(merged_mean_ci_data[[model]], merged_mean_ci_data$BCR_Percentage, method = "pearson", use = "complete.obs")
})

# Erstellung des finalen DataFrames mit den Korrelationen
correlation_df <- data.frame(
  model = names(correlations),
  correlation = correlations
)

ggplot(correlation_df, aes(x = reorder(model, correlation), y = correlation)) +
  geom_bar(stat = "identity", fill = "#00706d") +  
  geom_text(aes(label = round(correlation_df$correlation, 3)),  
            hjust = ifelse(correlation_df$correlation < 0, 1.2, -0.2),  
            color = "black", size = 4) +  
  coord_flip() +  
  labs(
    title = "Korrelation zwischen Modellen und BCR-Percentage",
    x = "Model",
    y = "Korrelation"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 12),  
    axis.text.x = element_text(angle = 0, hjust = 1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )


```





```{r dot plot for performance by data sets }

# Helper function to add two rows
add_extra_rows <- function(df) {
  # 1) Create an empty DF with the same columns (0 rows)
  new_df <- df[0, ]

  # 2) Add 3 new rows filled with NA
  new_df[1:3, ] <- NA

  # 3) Overwrite the columns of interest
  new_df$dataset <- c("pData + Block Data", "Block Data", "Pathway Data")
  new_df$model_class    <- df$model_class[1]

  # 4) Combine original data with the new rows
  rbind(df, new_df)
}


# 3) Add extra rows to core models
ov_results_cBoost_dot   <- add_extra_rows(ov_results_cBoost)
ov_results_coxph_dot    <- add_extra_rows(ov_results_coxph)
ov_results_DeepSurv_dot <- add_extra_rows(ov_results_DeepSurv)
ov_results_rsf_dot      <- add_extra_rows(ov_results_rsf)


# define needed columns
keep_cols <- c("dataset", "ci_coh1", "model_class")

# add CoxPAS und Priority Lasso
ov_results_cox_pas_dot <- ov_results_rsf_dot
ov_results_cox_pas_dot$model_class <- "Cox PASNet"
ov_results_cox_pas_dot[ , !(names(ov_results_cox_pas_dot) %in% keep_cols)] <- NA
ov_results_cox_pas_dot$ci_coh1 <- NA
ov_results_cox_pas_dot$ci_coh1[10] <- ov_results_coxPas$ci_coh1

ov_results_prio_dot <- ov_results_rsf_dot
ov_results_prio_dot$model_class <- "Priority Lasso"
ov_results_prio_dot[ , !(names(ov_results_prio_dot) %in% keep_cols)] <- NA
ov_results_prio_dot$ci_coh1 <- NA
ov_results_prio_dot$ci_coh1[c(8, 9)] <- ov_results_prio$ci_coh1

# 5) Combine all results (subset to relevant columns)
combined_results <- bind_rows(
  ov_results_cBoost_dot[, c("dataset", "ci_coh1", "model_class")],
  ov_results_coxph_dot[, c("dataset", "ci_coh1", "model_class")],
  ov_results_DeepSurv_dot[, c("dataset", "ci_coh1", "model_class")],
  ov_results_rsf_dot[, c("dataset", "ci_coh1", "model_class")],
  ov_results_cox_pas_dot[, c("dataset", "ci_coh1", "model_class")],
  ov_results_prio_dot[, c("dataset", "ci_coh1", "model_class")]
)



# 6) Plot
model_colors <- c(
  "CoxPH" = "black",
  "Priority Lasso" = "darkgrey",
  "Cox PASNet" = "lightgrey",
  "GBoost" = "red",  
  "DeepSurv" = "blue",  
  "RSF" = "green",  
  "Cox-PASNet" = "purple"
)

new_order <- c(
  "AutoEncoder",
  "pData_AutoEncoder",
  "Imputed",
  "pData_Imputed",
  "Intersection",
  "pData_Intersection",
  "pData",  
  "Block Data",
  "pData + Block Data",
  "Pathway Data"
)

# Reihenfolge explizit setzen
combined_results <- combined_results %>%
  mutate(dataset = factor(dataset, levels = new_order))

# Erstelle den Plot mit der neuen Reihenfolge
plot1 <- ggplot(
  data = combined_results %>%
    filter(!is.na(ci_coh1)) %>%
    mutate(ci_coh1 = as.numeric(ci_coh1)),
  aes(x = dataset, y = ci_coh1, color = model_class)
) +
  geom_point(size = 3) +
  scale_y_continuous(limits = c(0.6, 0.8), breaks = c(0.6, 0.7, 0.8)) +
  scale_x_discrete(
    labels = c(
      "AutoEncoder"       = "Autoencoder",
      "pData_AutoEncoder" = "Autoencoder + Clin. Data",
      "Imputed"            = "Common",
      "pData_Imputed"      = "Common + Clin. Data",
      "Intersection"         = "Intersect.",
      "pData_Intersection"   = "Intersect. + Clin. Data",
      "pData"             = "Clin. Data",
      "Block Data"          = "Block Data",
      "pData + Block Data" = "Block + Clin. Data",
      "Pathway Data"          = "Pathway + Clin. Data"
    )
  ) +
  scale_color_manual(values = model_colors) +  
  labs(
    title = "Performance of Models on Cohort 10 by Data Set",
    x = "Data Sets", y = "C-Index", color = "Model"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.box = "horizontal",
    legend.justification = "center",
    legend.margin = margin(t = 10, unit = "pt"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12)
  ) +
  guides(color = guide_legend(nrow = 1))

```


```{r Survival Curves for risk groups }


# extract times from one of the AE DeepSurv files (cohort1 high risk)
ae_surv_times_coh1 <- ae_deep_surv_survival_data_coh1_high_risk$time

# create DF for CoxPH survival (just cohort1 as example) and rename columns
cox_ch1 <- coxph_survival_data %>%
  select(time, cohort1_low_risk, cohort1_high_risk) %>%
  rename(
    Survival_CoxPH_LowRisk  = cohort1_low_risk,
    Survival_CoxPH_HighRisk = cohort1_high_risk
  )

# create DF for AE DeepSurv 
ae_deep_ch1 <- data.frame(
  time                     = ae_surv_times_coh1,
  Survival_DeepSurv_HighRisk = ae_surv_coh1_high_vec,
  Survival_DeepSurv_LowRisk  = ae_surv_coh1_low_vec
)

# merge both sets: get all unique times, then left_join
all_times_coh1 <- sort(unique(c(cox_ch1$time, ae_deep_ch1$time)))
survival_df_cohort1 <- data.frame(TimePoints = all_times_coh1)

survival_df_cohort1 <- survival_df_cohort1 %>%
  left_join(cox_ch1,    by = c("TimePoints" = "time")) %>%
  left_join(ae_deep_ch1,by = c("TimePoints" = "time")) %>%
  fill(
    Survival_CoxPH_LowRisk,  Survival_CoxPH_HighRisk,
    Survival_DeepSurv_LowRisk, Survival_DeepSurv_HighRisk,
    .direction = "down"
  )

# Plot survival curves
ggplot(survival_df_cohort1, aes(x = TimePoints)) +
  geom_line(aes(y = Survival_DeepSurv_LowRisk,  color = "DeepSurv Low Risk"),  linewidth = 1) +
  geom_line(aes(y = Survival_DeepSurv_HighRisk, color = "DeepSurv High Risk"), linewidth = 1) +
  geom_line(aes(y = Survival_CoxPH_LowRisk,     color = "CoxPH Low Risk"),     linewidth = 1) +
  geom_line(aes(y = Survival_CoxPH_HighRisk,    color = "CoxPH High Risk"),    linewidth = 1) +
  scale_linetype_manual(values = c(
    "DeepSurv Low Risk"  = "solid",
    "DeepSurv High Risk" = "dashed",
    "CoxPH Low Risk"     = "dotdash",
    "CoxPH High Risk"    = "dotted"
  )) +
  scale_color_manual(values = c(
    "DeepSurv Low Risk"  = "red", 
    "DeepSurv High Risk" = "#ffcd66", 
    "CoxPH Low Risk"     = "darkblue", 
    "CoxPH High Risk"    = "blue"
  )) +
  labs(
    title = "Cohort 10 Survival Curves for Risk Groups and Models",
    x     = "Months",
    y     = "Survival Probability",
    color = "Model & Risk Group"
  ) +
  theme_minimal() +
  theme(
    plot.title   = element_text(face = "bold", size = 12),
    legend.title = element_text(size = 12),
    legend.text  = element_text(size = 10),
    legend.position = "right"
  ) +
  scale_x_continuous(limits = c(0, 160))

```










